export const LocationTypeEnum = {
    RESIDENCE: 'RESIDENCE',
    BIRTH: 'BIRTH'
};

export const ContactTypeEnum = {
    PRO: "PRO",
    PERSO: "PERSO",
};

export const ContactNameEnum = {
    TELEGRAM: "TELEGRAM",
    INSTAGRAM: "INSTAGRAM",
    TWITTER: "TWITTER",
    TIKTOK: "TIKTOK",
    REDDIT: "REDDIT",
    SNAPCHAT: "SNAPCHAT",
    EMAIL: "EMAIL",
    WHATSAPP: "WHATSAPP",
};

export const ContactValidationRegex = {
    TELEGRAM: /^[a-zA-Z0-9_]{5,32}$/,
    INSTAGRAM: /^[a-zA-Z0-9._]{1,30}$/,
    TWITTER: /^@?[a-zA-Z0-9_]{1,15}$/,
    TIKTOK: /^[a-zA-Z0-9._]{1,24}$/,
    REDDIT: /^[A-Za-z0-9_-]{3,20}$/,
    SNAPCHAT: /^[a-zA-Z0-9._-]{3,15}$/
};

export const ExperienceEnum = {
    BEGINNER: 'BEGINNER',
    INTERMEDIATE: 'INTERMEDIATE',
    ADVANCED: 'ADVANCED',
    EXPERT: 'EXPERT'
};

export const EnglishLevelEnum = {
    A1: 'A1',
    A2: 'A2',
    B1: 'B1',
    B2: 'B2',
    C1: 'C1',
    C2: 'C2'
};

export const TimePerDayEnum = {
    H1_2: 'H1_2',
    H3_4: 'H3_4',
    H4_5: 'H4_5',
    H5_PLUS: 'H5_PLUS'
};

export const ContentKindEnum = {
    LINGERIE_NUDES: 'LINGERIE_NUDES',
    BDSM: 'BDSM',
    ANAL: 'ANAL',
    SOLO: 'SOLO',
    COUPLE: 'COUPLE'
};

export const PlatformTypeEnum = {
    ONLYFANS: 'ONLYFANS',
    MYM: 'MYM'
};

export const CountryCodeEnum = {
    AD: "AD",
    AE: "AE",
    AF: "AF",
    AG: "AG",
    AL: "AL",
    AM: "AM",
    AO: "AO",
    AR: "AR",
    AT: "AT",
    AU: "AU",
    AZ: "AZ",
    BA: "BA",
    BB: "BB",
    BD: "BD",
    BE: "BE",
    BF: "BF",
    BG: "BG",
    BH: "BH",
    BI: "BI",
    BJ: "BJ",
    BN: "BN",
    BO: "BO",
    BR: "BR",
    BS: "BS",
    BT: "BT",
    BW: "BW",
    BY: "BY",
    BZ: "BZ",
    CA: "CA",
    CF: "CF",
    CG: "CG",
    CH: "CH",
    CL: "CL",
    CM: "CM",
    CN: "CN",
    CO: "CO",
    CR: "CR",
    CU: "CU",
    CV: "CV",
    CY: "CY",
    CZ: "CZ",
    DE: "DE",
    DJ: "DJ",
    DK: "DK",
    DM: "DM",
    DO: "DO",
    DZ: "DZ",
    EC: "EC",
    EE: "EE",
    EG: "EG",
    ER: "ER",
    ES: "ES",
    ET: "ET",
    FI: "FI",
    FJ: "FJ",
    FM: "FM",
    FR: "FR",
    GA: "GA",
    GB: "GB",
    GE: "GE",
    GH: "GH",
    GM: "GM",
    GN: "GN",
    GQ: "GQ",
    GR: "GR",
    GT: "GT",
    GW: "GW",
    GY: "GY",
    HN: "HN",
    HR: "HR",
    HT: "HT",
    HU: "HU",
    ID: "ID",
    IE: "IE",
    IL: "IL",
    IN: "IN",
    IQ: "IQ",
    IR: "IR",
    IS: "IS",
    IT: "IT",
    JM: "JM",
    JO: "JO",
    JP: "JP",
    KE: "KE",
    KG: "KG",
    KH: "KH",
    KI: "KI",
    KM: "KM",
    KN: "KN",
    KP: "KP",
    KR: "KR",
    KW: "KW",
    KZ: "KZ",
    LA: "LA",
    LB: "LB",
    LC: "LC",
    LI: "LI",
    LK: "LK",
    LR: "LR",
    LS: "LS",
    LT: "LT",
    LU: "LU",
    LV: "LV",
    LY: "LY",
    MA: "MA",
    MC: "MC",
    MD: "MD",
    ME: "ME",
    MG: "MG",
    MH: "MH",
    MK: "MK",
    ML: "ML",
    MM: "MM",
    MN: "MN",
    MR: "MR",
    MT: "MT",
    MU: "MU",
    MV: "MV",
    MW: "MW",
    MX: "MX",
    MY: "MY",
    MZ: "MZ",
    NA: "NA",
    NE: "NE",
    NG: "NG",
    NI: "NI",
    NL: "NL",
    NO: "NO",
    NP: "NP",
    NR: "NR",
    NU: "NU",
    NZ: "NZ",
    OM: "OM",
    PA: "PA",
    PE: "PE",
    PG: "PG",
    PH: "PH",
    PK: "PK",
    PL: "PL",
    PT: "PT",
    PW: "PW",
    PY: "PY",
    QA: "QA",
    RO: "RO",
    RS: "RS",
    RU: "RU",
    RW: "RW",
    SA: "SA",
    SB: "SB",
    SC: "SC",
    SD: "SD",
    SE: "SE",
    SG: "SG",
    SI: "SI",
    SK: "SK",
    SL: "SL",
    SM: "SM",
    SN: "SN",
    SO: "SO",
    SR: "SR",
    ST: "ST",
    SV: "SV",
    SY: "SY",
    SZ: "SZ",
    TD: "TD",
    TG: "TG",
    TH: "TH",
    TJ: "TJ",
    TL: "TL",
    TM: "TM",
    TN: "TN",
    TO: "TO",
    TR: "TR",
    TT: "TT",
    TV: "TV",
    TZ: "TZ",
    UA: "UA",
    UG: "UG",
    US: "US",
    UY: "UY",
    UZ: "UZ",
    VA: "VA",
    VC: "VC",
    VE: "VE",
    VN: "VN",
    VU: "VU",
    WS: "WS",
    YE: "YE",
    ZA: "ZA",
    ZM: "ZM",
    ZW: "ZW"
};
